language: cpp
compiler:
  - clang
before_install:
  - cmake --version
install:
  - export CXXFLAGS="-std=c++11 -stdlib=libc++"
  - svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk@201601 libcxx
  - cd libcxx/lib && bash buildit
  - sudo cp ./libc++.so.1.0 /usr/lib/
  - sudo mkdir /usr/include/c++/v1
  - cd .. && sudo cp -r include/* /usr/include/c++/v1/
  - cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so
  - sudo ln -sf libc++.so.1.0 libc++.so.1
  - cd ~/build/AE9RB/dspp
before_script:
  - cmake .
script: make test_dspp && bin/test_dspp
branches:
  only:
    - master
os:
  - linux
